// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivebpevhrnkvoyoxqbje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2ZWJwZXZocm5rdm95b3hxYmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjgwMDYsImV4cCI6MjA2NTgwNDAwNn0.16WvFzI7VXLIgNs59ZGQo884HPausmU4noXgWzM2MZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);